### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by baff3r** [athphane/userbot#56]
`PermissionError: [Errno 13] Permission denied: '/proc/stat'`

**Comment by phoenixatom** [comment]
Are you trying to run the bot on an Android? Or a chrooted server?

**Comment by baff3r** [comment]
I have this error on my mobile phone, and my own server too

**Comment by phoenixatom** [comment]
It's because you don't have proper access to the cpu usage. You can fix it by fixing permissions on your server.

**Comment by OcroCodeChain** [comment]
python -m userbot 
Traceback (most recent call last):                                                 
File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\runpy.py", line  188, in _run_module_as_main                                                         mod_name, mod_spec, code = _get_module_details(mod_name, _Error)               
File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\runpy.py", line  147, in _get_module_details                                                         return _get_module_details(pkg_main_name, error)                               
File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\runpy.py", line  111, in _get_module_details                                                         __import__(pkg_name)                                                           
File "C:\Users\root\Documents\userbot\userbot\__init__.py", line 37, in  e>                                                                                   UserBot = UserBot(__version__)                                                 
File "C:\Users\root\Documents\userbot\userbot\userbot.py", line 22, in __init_ _                                                                                    super().__init__(                                                            
TypeError: __init__() got an unexpected keyword argument 'config_file'
--

**Comment by phoenixatom** [comment]
Looks liks you are missing the config.ini file.

**Comment by athphane** [comment]
@phoenixatom actually no. Pyrogram version 2 recently removed the ability to pass a config file to the main Client constructor. As a result the current codebase is breaking as there is no exact version specified on the requirements.txt file. 
 
 I will be releasing an update soon.
