### ISSUE TITLE
[BUG] config file is no longer supported in Pyrogram

### ISSUE THREAD

**Issue by phoenixatom** [athphane/userbot#58]
python -m userbot 
Traceback (most recent call last):                                                 
File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\runpy.py", line  188, in _run_module_as_main                                                         mod_name, mod_spec, code = _get_module_details(mod_name, _Error)               
File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\runpy.py", line  147, in _get_module_details                                                         return _get_module_details(pkg_main_name, error)                               
File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\runpy.py", line  111, in _get_module_details                                                         __import__(pkg_name)                                                           
File "C:\Users\root\Documents\userbot\userbot\__init__.py", line 37, in  e>                                                                                   UserBot = UserBot(__version__)                                                 
File "C:\Users\root\Documents\userbot\userbot\userbot.py", line 22, in __init_ _                                                                                    super().__init__(                                                            
TypeError: __init__() got an unexpected keyword argument 'config_file'
--

_Originally posted by @OcroCodeChain in https://github.com/athphane/userbot/issues/56#issuecomment-1126856993_

**Comment by athphane** [comment]
Fixed in 83473990e1afe96a4f347de164b9b0b337fe3624

CC: @OrcoCodeChain
